package com.example.culturemotelg.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_HOME = "home"
const val ROUTE_ADD_CLIENT = "addclient"
const val ROUTE_INFO_CLIENT = "infoclient"
const val ROUTE_VIEW_CLIENT = "viewclients"
const val ROUTE_UPDATE_CLIENT = "updateclient"
const val ROUTE_SPLASH = "splash"
const val ROUTE_CULTUREROOMS ="culture_rooms"
const val ROUTE_VIP_ROOMS_DETAIL = "vip_rooms_detail"
const val ROUTE_FULL_SCREEN_IMAGE = "fullscreen_image"
const val ROUTE_VVIP_ROOMS_DETAIL = "vvip_rooms_detail"
const val ROUTE_MASTERCLASS_ROOMS_DETAIL = "masterclass_rooms_detail"
const val ROUTE_BREAKFAST_SCREEN = "breakfast_screen"
const val ROUTE_LUNCH_SCREEN = "lunch_screen"
const val ROUTE_SUPPER_SCREEN = "supper_screen"
const val ROUTE_PARKING_SCREEN = "parking_screen"
const val ROUTE_CONSTUMERCARE_SCREEN = "constumercare_screen"
const val ROUTE_PAY = "payhere"
const val ROUTE_USERDASHBOARD = "user dashboard screen"